package workout.server.app.entity.constant;

public enum MuscleType {

    MUSCULI_COLLI,
    MUSCULUS_TRAPEZIUS,
    MUSCULUS_DELTOIDEUS_ANTERIOR,
    MEDIUS_MUSCULI_DELTOIDEI,
    POSTERIOR_DELTOIDEUS,
    MUSCULUS_PECTORALIS_MAJOR,
    MUSCULUS_BICEPS_BRACHII,
    MUSCULUS_TRICEPS_BRACHII,
    BRACHIUM_MUSCULI,
    MUSCULUS_LATISSIMUS_DORSI,
    INFERIORIS_DORSI_MUSCULI,
    MUSCULUS_RECTUS_ABDOMINIS,
    MUSCULUS_OBLIQUUS_EXTERNUS_ABDOMINIS,
    GLUTEUS_MAXIMUS,
    MUSCULUS_QUADRICEPS_FEMORIS,
    EXTRINSECUS_FEMUR_MUSCULUS,
    FEMUR_MUSCULI,
    MUSCULUS_BICEPS_BRACHII_FEMORIS,
    VITULUS_MUSCULUS,
    MUSCULUS_GASTROCNEMIUS
}
